# Generated by Django 3.2.7 on 2022-08-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skamdata',
            name='passwoard',
            field=models.CharField(default=1, max_length=160, verbose_name='name'),
            preserve_default=False,
        ),
    ]
