# Generated by Django 3.2.7 on 2022-08-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skam', '0002_skamdata_passwoard'),
    ]

    operations = [
        migrations.AddField(
            model_name='skamdata',
            name='country',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='skamdata',
            name='passwoard',
            field=models.CharField(max_length=160, verbose_name='passwoard'),
        ),
    ]
