# Generated by Django 3.2.7 on 2022-08-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skam', '0003_auto_20220810_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='skamdata',
            name='ip',
            field=models.TextField(default=''),
        ),
    ]
